# © Copyright 2025, 2026 Query Farm LLC - https://query.farm
#!/usr/bin/env python3

"""Emit src/methods.cpp: every VgiProtocol method with its wire schemas.

Derived from two generated-or-canonical sources rather than transcribed, because
a hand-maintained table of 70 methods drifts silently and the failure shows up
as a schema mismatch deep in dispatch:

  * `~/Development/vgi-python/vgi/protocol.py` — the `VgiProtocol` class, which
    is the protocol's definition. Its return annotation decides how a method
    answers (void / result / bytes / stream).
  * `src/generated/vgi_protocol_schemas.hpp` — the params and result schemas,
    themselves generated from the same Protocol by `vgi.codegen.cpp_schemas`.

Run after regenerating the headers:

    python3 scripts/regenerate_methods.py
"""

from __future__ import annotations

import pathlib
import re
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
VGI_PYTHON = pathlib.Path.home() / "Development" / "vgi-python"


def main() -> None:
    header = (ROOT / "src/generated/vgi_protocol_schemas.hpp").read_text()
    entries = re.findall(
        r"// Origin: method '([a-z_]+)' (params|result)\n"
        r"inline const std::shared_ptr<arrow::Schema> &(\w+)\(\)",
        header,
    )
    params = {m: fn for m, kind, fn in entries if kind == "params"}
    results = {m: fn for m, kind, fn in entries if kind == "result"}

    proto = (VGI_PYTHON / "vgi/protocol.py").read_text()
    proto = proto[proto.index("class VgiProtocol(Protocol):") :]
    sigs = re.findall(r"\n    def (\w+)\((.*?)\)\s*->\s*([^:]+):", proto, re.S)
    if not sigs:
        raise SystemExit("no methods parsed from VgiProtocol — did its shape change?")

    rows = []
    for name, _args, ret in sigs:
        ret = " ".join(ret.split())
        if name == "init":
            kind = "Stream"
        elif ret == "None":
            kind = "Void"
        elif ret.startswith("bytes"):
            kind = "Binary"
        else:
            kind = "Result"
        if name not in params:
            raise SystemExit(f"no params schema generated for {name}")
        if kind == "Result" and name not in results:
            raise SystemExit(f"no result schema generated for {name}")
        rows.append((name, kind, params[name], results.get(name), ret))

    lines = [
        "// © Copyright 2025, 2026 Query Farm LLC - https://query.farm",
        "//",
        "// GENERATED by scripts/regenerate_methods.py. DO NOT EDIT BY HAND.",
        "",
        '#include "methods.h"',
        "",
        "#include <arrow/type.h>",
        "",
        "#include <stdexcept>",
        "",
        '#include "generated/vgi_protocol_schemas.hpp"',
        "",
        "namespace vgi {",
        "namespace {",
        "namespace gen = ::vgi::generated;",
        "",
        "}  // namespace",
        "",
        "const std::shared_ptr<arrow::Schema>& envelope_schema() {",
        '    static const auto s = arrow::schema({arrow::field("result", arrow::binary())});',
        "    return s;",
        "}",
        "",
        "const std::shared_ptr<arrow::Schema>& payload_schema_of(const std::string& method) {",
        "    for (const auto& spec : protocol_methods()) {",
        "        if (spec.name == method) return spec.payload;",
        "    }",
        "    throw std::runtime_error(\"no such protocol method: \" + method);",
        "}",
        "",
        "const std::vector<MethodSpec>& protocol_methods() {",
        "    static const std::vector<MethodSpec> methods = {",
    ]
    for name, kind, p, r, ret in rows:
        if kind == "Result":
            res = f"gen::{r}()"
        else:
            # A Binary method's bytes are the payload; there is no inner schema.
            res = "kNoSchema"
        lines.append(
            f'        {{"{name}", MethodKind::{kind}, gen::{p}(), {res}}},  // -> {ret}'
        )
    lines += [
        "    };",
        "    return methods;",
        "}",
        "",
        "}  // namespace vgi",
        "",
    ]
    (ROOT / "src/methods.cpp").write_text("\n".join(lines))
    print(f"wrote {len(rows)} methods:", dict(Counter(k for _, k, _, _, _ in rows)))


if __name__ == "__main__":
    main()
