// © Copyright 2025-2026, Query.Farm LLC - https://query.farm
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/regenerate_methods.py. DO NOT EDIT BY HAND.

#include "methods.h"

#include <arrow/type.h>

#include <stdexcept>

#include "generated/vgi_protocol_schemas.hpp"

namespace vgi {
namespace {
namespace gen = ::vgi::generated;

}  // namespace

const std::shared_ptr<arrow::Schema>& envelope_schema() {
    static const auto s = arrow::schema({arrow::field("result", arrow::binary())});
    return s;
}

const std::shared_ptr<arrow::Schema>& payload_schema_of(const std::string& method) {
    for (const auto& spec : protocol_methods()) {
        if (spec.name == method) return spec.payload;
    }
    throw std::runtime_error("no such protocol method: " + method);
}

const std::vector<MethodSpec>& protocol_methods() {
    static const std::vector<MethodSpec> methods = {
        {"bind", MethodKind::Result, gen::BindParamsSchema(),
         gen::BindResultSchema()},  // -> BindResponse
        {"init", MethodKind::Stream, gen::InitParamsSchema(),
         kNoSchema},  // -> Stream[ProcessState, GlobalInitResponse]
        {"table_function_cardinality", MethodKind::Result,
         gen::TableFunctionCardinalityParamsSchema(),
         gen::TableFunctionCardinalityResultSchema()},  // -> TableCardinality
        {"table_function_statistics", MethodKind::Binary,
         gen::TableFunctionStatisticsParamsSchema(), kNoSchema},  // -> bytes | None
        {"table_function_dynamic_to_string", MethodKind::Result,
         gen::TableFunctionDynamicToStringParamsSchema(),
         gen::TableFunctionDynamicToStringResultSchema()},  // ->
                                                            // TableFunctionDynamicToStringResponse
        {"aggregate_bind", MethodKind::Result, gen::AggregateBindParamsSchema(),
         gen::AggregateBindResultSchema()},  // -> AggregateBindResponse
        {"aggregate_update", MethodKind::Result, gen::AggregateUpdateParamsSchema(),
         gen::AggregateUpdateResultSchema()},  // -> AggregateUpdateResponse
        {"aggregate_combine", MethodKind::Result, gen::AggregateCombineParamsSchema(),
         gen::AggregateCombineResultSchema()},  // -> AggregateCombineResponse
        {"aggregate_finalize", MethodKind::Result, gen::AggregateFinalizeParamsSchema(),
         gen::AggregateFinalizeResultSchema()},  // -> AggregateFinalizeResponse
        {"aggregate_destructor", MethodKind::Result, gen::AggregateDestructorParamsSchema(),
         gen::AggregateDestructorResultSchema()},  // -> AggregateDestructorResponse
        {"table_buffering_process", MethodKind::Result, gen::TableBufferingProcessParamsSchema(),
         gen::TableBufferingProcessResultSchema()},  // -> TableBufferingProcessResponse
        {"table_buffering_combine", MethodKind::Result, gen::TableBufferingCombineParamsSchema(),
         gen::TableBufferingCombineResultSchema()},  // -> TableBufferingCombineResponse
        {"table_buffering_destructor", MethodKind::Result,
         gen::TableBufferingDestructorParamsSchema(),
         gen::TableBufferingDestructorResultSchema()},  // -> TableBufferingDestructorResponse
        {"aggregate_window_init", MethodKind::Result, gen::AggregateWindowInitParamsSchema(),
         gen::AggregateWindowInitResultSchema()},  // -> AggregateWindowInitResponse
        {"aggregate_window", MethodKind::Result, gen::AggregateWindowParamsSchema(),
         gen::AggregateWindowResultSchema()},  // -> AggregateWindowResponse
        {"aggregate_window_destructor", MethodKind::Result,
         gen::AggregateWindowDestructorParamsSchema(),
         gen::AggregateWindowDestructorResultSchema()},  // -> AggregateWindowDestructorResponse
        {"aggregate_window_batch", MethodKind::Result, gen::AggregateWindowBatchParamsSchema(),
         gen::AggregateWindowBatchResultSchema()},  // -> AggregateWindowBatchResponse
        {"aggregate_streaming_open", MethodKind::Result, gen::AggregateStreamingOpenParamsSchema(),
         gen::AggregateStreamingOpenResultSchema()},  // -> AggregateStreamingOpenResponse
        {"aggregate_streaming_chunk", MethodKind::Result,
         gen::AggregateStreamingChunkParamsSchema(),
         gen::AggregateStreamingChunkResultSchema()},  // -> AggregateStreamingChunkResponse
        {"aggregate_streaming_close", MethodKind::Result,
         gen::AggregateStreamingCloseParamsSchema(),
         gen::AggregateStreamingCloseResultSchema()},  // -> AggregateStreamingCloseResponse
        {"catalog_catalogs", MethodKind::Result, gen::CatalogCatalogsParamsSchema(),
         gen::CatalogCatalogsResultSchema()},  // -> CatalogsResponse
        {"catalog_attach", MethodKind::Result, gen::CatalogAttachParamsSchema(),
         gen::CatalogAttachResultSchema()},  // -> CatalogAttachResult
        {"catalog_detach", MethodKind::Void, gen::CatalogDetachParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_create", MethodKind::Void, gen::CatalogCreateParamsSchema(),
         kNoSchema},                                                                    // -> None
        {"catalog_drop", MethodKind::Void, gen::CatalogDropParamsSchema(), kNoSchema},  // -> None
        {"catalog_version", MethodKind::Result, gen::CatalogVersionParamsSchema(),
         gen::CatalogVersionResultSchema()},  // -> CatalogVersionResponse
        {"catalog_transaction_begin", MethodKind::Result,
         gen::CatalogTransactionBeginParamsSchema(),
         gen::CatalogTransactionBeginResultSchema()},  // -> TransactionBeginResponse
        {"catalog_transaction_commit", MethodKind::Void,
         gen::CatalogTransactionCommitParamsSchema(), kNoSchema},  // -> None
        {"catalog_transaction_rollback", MethodKind::Void,
         gen::CatalogTransactionRollbackParamsSchema(), kNoSchema},  // -> None
        {"catalog_schemas", MethodKind::Result, gen::CatalogSchemasParamsSchema(),
         gen::CatalogSchemasResultSchema()},  // -> SchemasResponse
        {"catalog_schema_get", MethodKind::Result, gen::CatalogSchemaGetParamsSchema(),
         gen::CatalogSchemaGetResultSchema()},  // -> SchemasResponse
        {"catalog_schema_create", MethodKind::Void, gen::CatalogSchemaCreateParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_schema_drop", MethodKind::Void, gen::CatalogSchemaDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_schema_contents_tables", MethodKind::Result,
         gen::CatalogSchemaContentsTablesParamsSchema(),
         gen::CatalogSchemaContentsTablesResultSchema()},  // -> TablesResponse
        {"catalog_schema_contents_views", MethodKind::Result,
         gen::CatalogSchemaContentsViewsParamsSchema(),
         gen::CatalogSchemaContentsViewsResultSchema()},  // -> ViewsResponse
        {"catalog_schema_contents_functions", MethodKind::Result,
         gen::CatalogSchemaContentsFunctionsParamsSchema(),
         gen::CatalogSchemaContentsFunctionsResultSchema()},  // -> FunctionsResponse
        {"catalog_copy_from_formats", MethodKind::Result, gen::CatalogCopyFromFormatsParamsSchema(),
         gen::CatalogCopyFromFormatsResultSchema()},  // -> CopyFromFormatsResponse
        {"catalog_table_get", MethodKind::Result, gen::CatalogTableGetParamsSchema(),
         gen::CatalogTableGetResultSchema()},  // -> TablesResponse
        {"catalog_table_create", MethodKind::Void, gen::CatalogTableCreateParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_drop", MethodKind::Void, gen::CatalogTableDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_scan_function_get", MethodKind::Binary,
         gen::CatalogTableScanFunctionGetParamsSchema(), kNoSchema},  // -> bytes
        {"catalog_table_scan_branches_get", MethodKind::Binary,
         gen::CatalogTableScanBranchesGetParamsSchema(), kNoSchema},  // -> bytes
        {"catalog_table_column_statistics_get", MethodKind::Binary,
         gen::CatalogTableColumnStatisticsGetParamsSchema(), kNoSchema},  // -> bytes | None
        {"catalog_table_insert_function_get", MethodKind::Binary,
         gen::CatalogTableInsertFunctionGetParamsSchema(), kNoSchema},  // -> bytes
        {"catalog_table_update_function_get", MethodKind::Binary,
         gen::CatalogTableUpdateFunctionGetParamsSchema(), kNoSchema},  // -> bytes
        {"catalog_table_delete_function_get", MethodKind::Binary,
         gen::CatalogTableDeleteFunctionGetParamsSchema(), kNoSchema},  // -> bytes
        {"catalog_table_comment_set", MethodKind::Void, gen::CatalogTableCommentSetParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_column_comment_set", MethodKind::Void,
         gen::CatalogTableColumnCommentSetParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_rename", MethodKind::Void, gen::CatalogTableRenameParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_column_add", MethodKind::Void, gen::CatalogTableColumnAddParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_column_drop", MethodKind::Void, gen::CatalogTableColumnDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_table_column_rename", MethodKind::Void,
         gen::CatalogTableColumnRenameParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_column_default_set", MethodKind::Void,
         gen::CatalogTableColumnDefaultSetParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_column_default_drop", MethodKind::Void,
         gen::CatalogTableColumnDefaultDropParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_column_type_change", MethodKind::Void,
         gen::CatalogTableColumnTypeChangeParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_not_null_drop", MethodKind::Void,
         gen::CatalogTableNotNullDropParamsSchema(), kNoSchema},  // -> None
        {"catalog_table_not_null_set", MethodKind::Void, gen::CatalogTableNotNullSetParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_view_get", MethodKind::Result, gen::CatalogViewGetParamsSchema(),
         gen::CatalogViewGetResultSchema()},  // -> ViewsResponse
        {"catalog_view_create", MethodKind::Void, gen::CatalogViewCreateParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_view_drop", MethodKind::Void, gen::CatalogViewDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_view_rename", MethodKind::Void, gen::CatalogViewRenameParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_view_comment_set", MethodKind::Void, gen::CatalogViewCommentSetParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_macro_get", MethodKind::Result, gen::CatalogMacroGetParamsSchema(),
         gen::CatalogMacroGetResultSchema()},  // -> MacrosResponse
        {"catalog_macro_create", MethodKind::Void, gen::CatalogMacroCreateParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_macro_drop", MethodKind::Void, gen::CatalogMacroDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_schema_contents_macros", MethodKind::Result,
         gen::CatalogSchemaContentsMacrosParamsSchema(),
         gen::CatalogSchemaContentsMacrosResultSchema()},  // -> MacrosResponse
        {"catalog_index_get", MethodKind::Result, gen::CatalogIndexGetParamsSchema(),
         gen::CatalogIndexGetResultSchema()},  // -> IndexesResponse
        {"catalog_index_create", MethodKind::Void, gen::CatalogIndexCreateParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_index_drop", MethodKind::Void, gen::CatalogIndexDropParamsSchema(),
         kNoSchema},  // -> None
        {"catalog_schema_contents_indexes", MethodKind::Result,
         gen::CatalogSchemaContentsIndexesParamsSchema(),
         gen::CatalogSchemaContentsIndexesResultSchema()},  // -> IndexesResponse
    };
    return methods;
}

}  // namespace vgi
